"""
run_ntop_automate.py
------------------------------------------------------------------------
Generate the cylindrical gyroid HX meshes with cyl_gyroid_hx.py, then run
an nTop notebook headless with nTop Automate (nTopCL) to turn each mesh
into an implicit body and export it.

nTop Automate runs an EXISTING .ntop notebook whose variables were marked
as inputs; it cannot build a notebook from scratch. Build the notebook
once in the nTop GUI (see README_ntop.md, "Notebook for nTop Automate"),
then run from VS Code:

    python run_ntop_automate.py --ntop "C:/Program Files/nTopology/nTopology/nTopCL.exe" \
        --notebook hx_import.ntop

Options:
    --skip-export        reuse STLs already in --mesh-dir
    --voxel 0.2          resolution passed to cyl_gyroid_hx.py
    --template FILE      input JSON generated by nTopCL for your notebook;
                         values are filled in by input name (recommended:
                         nTop versions differ in the exact JSON fields)

The default JSON layout below follows nTop's published examples
({"description", "inputs": [{"name", "type", "value"}]}). If nTopCL
rejects it, generate the template for your notebook with nTopCL (see
`nTopCL.exe --help`) and pass it with --template.
------------------------------------------------------------------------
"""

import argparse
import json
import os
import subprocess
import sys

import cyl_gyroid_hx as hx

# Input names exactly as you named them in the nTop notebook
IN_MESH = "Mesh Path"
IN_OUT = "Output Path"


def build_inputs(mesh_path, out_path, template=None):
    if template:
        with open(template) as f:
            data = json.load(f)
        found = set()
        for item in data.get("inputs", []):
            if item.get("name") == IN_MESH:
                item["value"] = mesh_path
                found.add(IN_MESH)
            elif item.get("name") == IN_OUT:
                item["value"] = out_path
                found.add(IN_OUT)
        missing = {IN_MESH, IN_OUT} - found
        if missing:
            sys.exit(f"Template has no input named {sorted(missing)}; "
                     f"rename the notebook inputs or edit IN_MESH / IN_OUT.")
        return data
    return {"description": "Cylindrical gyroid HX import",
            "inputs": [{"name": IN_MESH, "type": "text", "value": mesh_path},
                       {"name": IN_OUT, "type": "text", "value": out_path}]}


def run_ntop(ntopcl, notebook, inputs, work_dir, tag):
    in_json = os.path.join(work_dir, f"{tag}_input.json")
    out_json = os.path.join(work_dir, f"{tag}_output.json")
    with open(in_json, "w") as f:
        json.dump(inputs, f, indent=2)
    cmd = [ntopcl, "-j", in_json, "-o", out_json, notebook]
    print(" ".join(f'"{c}"' if " " in c else c for c in cmd))
    res = subprocess.run(cmd, capture_output=True, text=True)
    print(res.stdout)
    if res.returncode != 0:
        print(res.stderr)
        sys.exit(f"nTopCL failed for {tag} (exit {res.returncode})")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ntop", required=True, help="path to nTopCL.exe")
    ap.add_argument("--notebook", required=True, help=".ntop notebook with inputs")
    ap.add_argument("--mesh-dir", default=hx.OUT_DIR)
    ap.add_argument("--out-dir", default="ntop_output")
    ap.add_argument("--voxel", type=float, default=hx.VOXEL)
    ap.add_argument("--template", default=None)
    ap.add_argument("--skip-export", action="store_true")
    ap.add_argument("--solid-only", action="store_true",
                    help="process HX_solid only (skip fluid domains)")
    a = ap.parse_args()

    if not a.skip_export:
        hx.export(a.voxel, a.mesh_dir, fluids=not a.solid_only)

    os.makedirs(a.out_dir, exist_ok=True)
    names = ["HX_solid"] + ([] if a.solid_only else ["Hot_fluid", "Cold_fluid"])
    for n in names:
        mesh = os.path.abspath(os.path.join(a.mesh_dir, f"{n}.stl"))
        if not os.path.exists(mesh):
            sys.exit(f"missing {mesh} - run without --skip-export first")
        out = os.path.abspath(os.path.join(a.out_dir, f"{n}_ntop.stl"))
        run_ntop(a.ntop, a.notebook, build_inputs(mesh, out, a.template),
                 a.out_dir, n)
        print(f"{n}: done -> {out}")


if __name__ == "__main__":
    main()
